services:

  app:
    build: 
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    env_file:
      - .postgres.env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - xpack.security.enabled=false
    ports:
      - ${ELS_PORT}:${ELS_PORT}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # restart: unless-stopped

volumes:
  pgdata:
  esdata: