import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddTracklistsToEpisodes0010071714943408363
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const episodes = await queryRunner.query(
      `SELECT id FROM episode ORDER BY EPISODE ASC LIMIT 100`,
    );

    const tracks = [
      `(1, 'Warrior', 'Voodoo (Oliver Lieb mix)', 'Incentive promo', '${episodes[1].id}')`,
      `(2, 'Munity', 'Secrets (Ian Wilkie mix)', '', '${episodes[1].id}')`,
      `(3, 'Joker Jam', 'Innocense (Planisphere mix)', '', '${episodes[1].id}')`,
      `(4, 'Liquidation', 'Theme from Liquid (Marco V. mix)', 'Acetate', '${episodes[1].id}')`,
      `(5, 'Sonic Inc.', 'Taste of Summer', 'Bonzai Promo', '${episodes[1].id}')`,
      `(6, 'Natural Born Grooves', 'Kickback (TDR remix)', 'Spinnin'' promo', '${episodes[1].id}')`,
      `(7, 'RR Workshop', '50K (promo)', '', '${episodes[1].id}')`,
      `(8, 'Ultimate Seduction', 'Ultimate Seduction', '', '${episodes[1].id}')`,
      `(9, 'System F. feat. Armin van Buuren', 'Exhale (new mix)', 'Acetate', '${episodes[1].id}')`,
      `(10, 'Blank & Jones', 'Tribal Attack', '', '${episodes[1].id}')`,
      `(11, 'Drax & Scott Mac', 'Sublime (Darkstar remix)', 'Spot on', '${episodes[1].id}')`,
      `(12, 'Orion', 'See me Here', 'Incentive', '${episodes[1].id}')`,
      `(13, 'Praha presents Kian', 'Pachinko Part two', 'Platipus', '${episodes[1].id}')`,
      `(14, '?', 'Clear Blue Moon', 'Acetate', '${episodes[1].id}')`,
      `(15, 'Ralphie B.', 'Massive', 'Blackhole promo', '${episodes[1].id}')`,
      `(16, '?', 'Members of Mayday (Paul van Dijk mix)', 'Promo', '${episodes[1].id}')`,
      `(17, 'Rank1', 'Such is Life', 'Free for All-promo', '${episodes[1].id}')`,
      `(18, 'S.O.L.I.S.', 'Dolphins (Classified Project remix)', 'Alien Promo', '${episodes[1].id}')`,
      `(19, 'Armin van Buuren', 'Blue Fear', 'Cyber Records', '${episodes[1].id}')`,
      `(1, 'Cyclone', 'Salobre', 'Transk promo', '${episodes[2].id}')`,
      `(2, 'The Infernal Machine', 'Realistic (Infernal machine remix)', 'Positiva promo', '${episodes[2].id}')`,
      `(3, 'Sister Bliss feat. John Martyn', 'Deliver Me (Lee Combs mix)', 'Blackhole', '${episodes[2].id}')`,
      `(4, 'Perpetuous Dreamer', 'The Sound of Goodbye (Armin van Buuren''s Rising Star mix)', 'Armind promo', '${episodes[2].id}')`,
      `(5, 'Signum', '?', 'promo BPM', '${episodes[2].id}')`,
      `(6, 'Mystique vs. U2', 'New Years Dub (Hybrid mix)', 'Serious promo', '${episodes[2].id}')`,
      `(7, 'Capricorn', '20 Hz (Global Cuts, 1993)', '', '${episodes[2].id}')`,
      `(8, 'Mauro Picotto', 'Verdi', 'BXR', '${episodes[2].id}')`,
      `(9, 'Taktic vs. Soulsearcher', 'Can''t get enough', '', '${episodes[2].id}')`,
      `(10, 'Satoshi Tomiie', 'Love in Traffic', '', '${episodes[2].id}')`,
      `(11, 'Natious', 'Another World', '', '${episodes[2].id}')`,
      `(12, 'Sonic Inc.', 'The Taste of Summer', '', '${episodes[2].id}')`,
      `(13, 'Ralphie B.', 'Massive', 'promo Blackhole', '${episodes[2].id}')`,
      `(14, 'Airwave', 'Save Me', 'Bonzai', '${episodes[2].id}')`,
      `(15, 'Mike Vandenberg', 'Flightpath (DJ Remy Remix)', 'Sadie', '${episodes[2].id}')`,
      `(16, 'Speedy J.', 'Electric Deluxe', '+8', '${episodes[2].id}')`,
      `(17, '?', 'Clear Blue Moon', 'Acetate', '${episodes[2].id}')`,
      `(18, 'Schiller', 'Ruhe (Humate Remix)', '', '${episodes[2].id}')`,
      `(1, 'Jan Johnson', 'New York', 'Alphabet City promo', '${episodes[3].id}')`,
      `(2, 'M', 'Promo', 'Combined Forces', '${episodes[3].id}')`,
      `(3, 'Cape Town', 'Stringrizer', 'Bonzai', '${episodes[3].id}')`,
      `(4, '?', '?', '', '${episodes[3].id}')`,
      `(5, 'Orion', 'See Me Here', 'Incentive Promo', '${episodes[3].id}')`,
      `(6, 'Ralphie B.', 'Massive', 'Blackhole promo', '${episodes[3].id}')`,
      `(7, 'Perpetuous Dreamer', 'The Sound of Goodbye (Armin van Buuren''s Tribal Feel Vocal)', 'Armind Promo', '${episodes[3].id}')`,
      `(8, 'Warrior', 'Voodoo (Oliver Lieb Mix)', 'Incentive promo', '${episodes[3].id}')`,
      `(9, 'Underworld', 'Dark & Long (JBO, 1994)', '', '${episodes[3].id}')`,
      `(10, 'System F. feat. Armin van Buuren', 'Exhale (Ferry Corsten & Armin van Buuren new mix)', 'Acetate', '${episodes[3].id}')`,
      `(11, '?', 'Startheme', 'Armind/ Acetate', '${episodes[3].id}')`,
      `(12, 'Evolution', 'Crocodile man', '', '${episodes[3].id}')`,
      `(13, 'Sister Bliss feat. John Martyn', 'Deliver Me (Lee Combs mix)', 'Blackhole', '${episodes[3].id}')`,
      `(14, 'Sonic Inc.', 'Taste of Summer', '', '${episodes[3].id}')`,
      `(15, 'Infernal Machine', 'Realistic (Infernal machine remix)', 'Positiva promo', '${episodes[3].id}')`,
      `(16, 'Voodoo Dildo', 'Have I told you?', '', '${episodes[3].id}')`,
      `(17, 'Signum', '?', 'promo BPM', '${episodes[3].id}')`,
      `(18, '?', 'Clear Blue Moon', 'Armind/ Acetate', '${episodes[3].id}')`,
      `(19, 'Liquidation', 'Theme from Liquid (Marco V. mix)', 'Acetate/ United', '${episodes[3].id}')`,
      `(1, 'Perpetuous Dreamer', 'The Sound of Goodbye (Armin''s Tribal Feel)', 'Armind/ United', '${episodes[4].id}')`,
      `(2, 'Orinoko', 'island remix (Saints & Sinners Remix)', '', '${episodes[4].id}')`,
      `(3, 'Sonic Inc.', 'A Taste of Summer', 'Bonzai promo', '${episodes[4].id}')`,
      `(4, 'Solid Sessions', 'Janeiro (Pronti & Kalmani Vocal mix)', 'Combined Forces Promo', '${episodes[4].id}')`,
      `(5, 'Ralphie B.', 'Massive', 'Blackhole Promo', '${episodes[4].id}')`,
      `(6, 'Rank1', 'Such is Life (Marco V. Remix)', 'Free For All Promo', '${episodes[4].id}')`,
      `(7, 'Humate', 'Love Stimulation (Paul van Dijk remix)', 'MFS, 1993', '${episodes[4].id}')`,
      `(8, 'Spicelab', 'Oscilator', 'Testified', '${episodes[4].id}')`,
      `(9, '4 strings', 'Into the night', 'Liquid promo', '${episodes[4].id}')`,
      `(10, 'Electric Tease', 'Fever', 'Automatic Promo', '${episodes[4].id}')`,
      `(11, 'Hi End System', 'Lost', 'TicToc Records', '${episodes[4].id}')`,
      `(12, 'Greencourt feat. De/Vision', 'Take (My Breath Away) (Chrome Remix)', '', '${episodes[4].id}')`,
      `(13, 'Tata Box Inhibitors', 'Plasmids (Force Mass Motion remix)', 'Future Groove', '${episodes[4].id}')`,
      `(14, 'Marc Auerback presents Muke', '?', 'Mode Records', '${episodes[4].id}')`,
      `(15, 'Orion', 'See Me Here (Skope''s Remix)', 'Incentive', '${episodes[4].id}')`,
      `(16, 'Cape Town', 'Stringrizer', 'Bonzai promo', '${episodes[4].id}')`,
      `(17, 'Photon Project', 'The Outside', 'Blackhole', '${episodes[4].id}')`,
      `(18, 'Jaya', 'Excursion (Original mix)', 'Inversus', '${episodes[4].id}')`,
      `(19, 'Moogwai', 'The Labyrinth Part two', 'Platipus', '${episodes[4].id}')`,
      `(20, '?', 'Clear Blue Moon', 'Armind/Acetate', '${episodes[4].id}')`,
      `(1, 'Greed feat. Lesly', 'Fatal', '', '${episodes[5].id}')`,
      `(2, 'Solid Sessions', 'Janeiro (Pronti & Kalmani mix vocal mix)', 'combined forces', '${episodes[5].id}')`,
      `(3, '4 Strings', 'Into the night', 'Spinnin'' promo', '${episodes[5].id}')`,
      `(4, 'Alibi', 'Eternity (Thrillseekers remix)', 'Armind/ Vandit', '${episodes[5].id}')`,
      `(5, 'Sonic Inc.', 'A Taste of Summer', 'Bonzai', '${episodes[5].id}')`,
      `(6, 'Vincent de Moor', 'Flowtation 2001', 'Combined Forces', '${episodes[5].id}')`,
      `(7, 'Perpetuous Dreamer', 'The Sound Of Goodbye (Above & Beyond remix)', 'Armind/ Cream UK', '${episodes[5].id}')`,
      `(8, 'Jam & Spoon', 'Stella', 'R&S, 1993', '${episodes[5].id}')`,
      `(9, 'Ralphie B.', 'Massive', 'Blackhole', '${episodes[5].id}')`,
      `(10, 'Freefall', 'Skydive (Warrior remix)', 'Incentive promo', '${episodes[5].id}')`,
      `(11, 'John Creamer & Stephane K feat. Oliver Twisted', 'I love you (ambient mix)', '', '${episodes[5].id}')`,
      `(12, 'Jimmy van M.', '?', '', '${episodes[5].id}')`,
      `(13, 'Orinoko', 'Island remix (Saints & Sinners remix)', 'Positiva', '${episodes[5].id}')`,
      `(14, 'Walter Solo', 'Coming from another world', 'captivating sounds/warner', '${episodes[5].id}')`,
      `(15, 'Lemon8', 'Pressure', 'basic beat', '${episodes[5].id}')`,
      `(16, 'DJ Nukem vs. Chab', 'Forward (piece process remix)', 'cyber records promo', '${episodes[5].id}')`,
      `(17, 'Capetown', 'Stringrizer', 'Bonzai', '${episodes[5].id}')`,
      `(18, 'Dirty Vegas', 'Days Go By (Lucien Foort remix)', '', '${episodes[5].id}')`,
      `(19, 'Trisco', 'Musak (Steve Lawler remix)', '', '${episodes[5].id}')`,
      `(20, 'Rank1', 'Such is Life (rank1 dub)', '', '${episodes[5].id}')`,
      `(21, 'Spicelab', 'Oscillator EP', '', '${episodes[5].id}')`,
      `(22, 'Signum', '5 yards', 'Jinx', '${episodes[5].id}')`,
      `(23, 'Barthezz', 'on the move (Riva remix)', '', '${episodes[5].id}')`,
      `(1, 'Solid Sessions', 'Janeiro (Pronti & Kalmani remix)', 'Combined Forces promo', '${episodes[6].id}')`,
      `(2, '?', 'Ibeatza', '', '${episodes[6].id}')`,
      `(3, '4 Strings', 'Into the Night', 'Spinnin''', '${episodes[6].id}')`,
      `(4, 'System F.', 'Theme Dance Valley 2001', 'Tsunami promo', '${episodes[6].id}')`,
      `(5, 'Push', 'The Legacy', 'Bonzai Promo', '${episodes[6].id}')`,
      `(6, 'Starecase', 'Navigator', 'Hope', '${episodes[6].id}')`,
      `(7, 'Unknown', 'Souvenir de Chine', 'Bonzai promo', '${episodes[6].id}')`,
      `(8, 'Carl Craig presents Paperclip People', 'Throw', 'Planet E/1994', '${episodes[6].id}')`,
      `(9, 'Rising Star', 'Clear Blue Moon', 'Armind Promo/United', '${episodes[6].id}')`,
      `(10, 'Faithless', 'We Come 1 (Dave Clarke remix)', 'Cheeky limited', '${episodes[6].id}')`,
      `(11, 'Rocco & Heist', 'Rescue Me (Oliver Lieb remix)', '', '${episodes[6].id}')`,
      `(12, 'Monoboy feat Delores', 'The Music in You (Oliver Klein remix)', 'perfecto', '${episodes[6].id}')`,
      `(13, 'Private Taste', 'First', 'automatic promo', '${episodes[6].id}')`,
      `(14, 'Sasha & Emerson', 'Scorchio (Sander Kleinenberg mix)', 'Deconstruction', '${episodes[6].id}')`,
      `(15, 'Ballroom', 'Come Along (Chrome mix)', 'underworld records', '${episodes[6].id}')`,
      `(16, 'Accadia', 'Into the dawn (James Holden remix)', 'Lost Language', '${episodes[6].id}')`,
      `(17, 'Medea feat. Justine', 'Universal', 'ATCR promo', '${episodes[6].id}')`,
      `(18, 'Mutekki', 'no.6 Aron Akira', '', '${episodes[6].id}')`,
      `(19, 'SF 10300', 'Kolo (Oliver Moldan remix)', 'Superfly', '${episodes[6].id}')`,
      `(20, 'Complex Climate', 'From the heart and the mind', 'Bonzai limited', '${episodes[6].id}')`,
      `(21, 'Walter Solo', 'Coming from another World (DJ Astrid remix)', 'promo captivating sounds', '${episodes[6].id}')`,
      `(22, 'Virtua Trancer', 'Sex After Dinner', 'Bonzai promo', '${episodes[6].id}')`,
      `(23, 'Rank1', 'Such is Life (Dub)', '', '${episodes[6].id}')`,
      `(1, 'Tall Paul vs. INXS', 'Precious Heart (original mix)', 'edel promo', '${episodes[7].id}')`,
      `(2, 'Shane', 'Too late to turn', 'Reef promo', '${episodes[7].id}')`,
      `(3, 'DJ Cyber', 'Marco Antonio', 'Cyber Acetate', '${episodes[7].id}')`,
      `(4, 'Push', 'The Legacy', 'Bonzai Promo', '${episodes[7].id}')`,
      `(5, '?', 'Ibeatza', '', '${episodes[7].id}')`,
      `(6, 'Accadia', 'Into the dawn (James Holden remix)', 'Lost Language', '${episodes[7].id}')`,
      `(7, 'Nick K. vs. Kid Vicious', '?', 'Tsunami promo', '${episodes[7].id}')`,
      `(8, 'Der Dritte Raum', 'Trommelmachine', 'Eye-Q/ 1996', '${episodes[7].id}')`,
      `(9, 'Alibi', 'Eternity (Thrillseekers remix)', 'Armind/ Vandit', '${episodes[7].id}')`,
      `(10, 'System F.', 'Theme Dance Valley 2001', 'Tsunami promo', '${episodes[7].id}')`,
      `(11, 'Stylus Trouble', 'Sputnik (mainframe remix)', 'Junior London', '${episodes[7].id}')`,
      `(12, 'Way Out West', 'Intensify (Peace Division remix)', 'Blackhole promo', '${episodes[7].id}')`,
      `(13, 'DJ Remy', 'Radiate (Mike Monday remix)', 'Additive', '${episodes[7].id}')`,
      `(14, 'Orinoko', 'Island (Saints & Sinners remix)', 'Positiva', '${episodes[7].id}')`,
      `(15, 'Rising Star', 'Startheme', 'Armind promo', '${episodes[7].id}')`,
      `(16, 'Christian Hornborstel', 'Back to the music (tough & twisted remix)', 'southeast promo', '${episodes[7].id}')`,
      `(17, 'Connector', 'Interference', 'Spinnin promo', '${episodes[7].id}')`,
      `(18, 'Unknown', 'Souvenir de Chine', 'Bonzai promo', '${episodes[7].id}')`,
      `(19, 'Mutekki', 'no.6 Aron Akira', 'Mutekki/ UCMG', '${episodes[7].id}')`,
      `(20, 'Vincent de Moor', 'Flowtation 2001', 'Combined Forces', '${episodes[7].id}')`,
      `(21, 'Faithless', 'We Come 1 (Dave Clarke remix)', 'Cheeky limited', '${episodes[7].id}')`,
      `(22, 'Complex Climate', 'From the heart and the mind', 'Bonzai limited', '${episodes[7].id}')`,
    ];

    await queryRunner.query(
      `INSERT INTO track (number, artist, title, label, episodeId) VALUES ${tracks.join(', ')}`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM track`);
  }
}
